# Generated by Django 3.0 on 2019-12-17 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TrustedParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('activity_distinctions', models.TextField(blank=True, null=True)),
                ('activity_educations', models.TextField(blank=True, null=True)),
                ('activity_employments', models.TextField(blank=True, null=True)),
                ('activity_fundings', models.TextField(blank=True, null=True)),
                ('activity_invited_positions', models.TextField(blank=True, null=True)),
                ('activity_memberships', models.TextField(blank=True, null=True)),
                ('activity_peer_reviews', models.TextField(blank=True, null=True)),
                ('activity_qualifications', models.TextField(blank=True, null=True)),
                ('activity_research_resources', models.TextField(blank=True, null=True)),
                ('activity_services', models.TextField(blank=True, null=True)),
                ('activity_works', models.TextField(blank=True, null=True)),
                ('person_addresses', models.TextField(blank=True, null=True)),
                ('person_biography', models.TextField(blank=True, null=True)),
                ('person_emails', models.TextField(blank=True, null=True)),
                ('person_external_identifiers', models.TextField(blank=True, null=True)),
                ('person_keywords', models.TextField(blank=True, null=True)),
                ('person_other_names', models.TextField(blank=True, null=True)),
                ('person_researcher_urls', models.TextField(blank=True, null=True)),
                ('virta_publications', models.TextField(blank=True, default='[]', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='researchprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('publicationYear', models.PositiveSmallIntegerField(null=True)),
                ('includeInProfile', models.BooleanField(default=False)),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='research.Origin')),
                ('researchprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='research.ResearchProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PortalPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_person_info', models.BooleanField(default=True, verbose_name='Nimi ja tunnisteet')),
                ('show_research_description', models.BooleanField(default=True, verbose_name='Tutkimustoiminnan kuvaus')),
                ('show_organization', models.BooleanField(default=True, verbose_name='Organisaatio')),
                ('show_education', models.BooleanField(default=True, verbose_name='Tutkinnot')),
                ('show_works', models.BooleanField(default=True, verbose_name='Julkaisut')),
                ('show_research_resources', models.BooleanField(default=True, verbose_name='Tutkimusaineistot')),
                ('show_fundings', models.BooleanField(default=True, verbose_name='Hankkeet')),
                ('show_infrastuctures', models.BooleanField(default=True, verbose_name='Tutkimusinfrastruktuurit')),
                ('show_other_activities', models.BooleanField(default=True, verbose_name='Muut tutkimusaktiviteetit')),
                ('trusted_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_permission', to='research.TrustedParty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'trusted_party')},
            },
        ),
    ]
