# Generated by Django 3.0.1 on 2020-09-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employment',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitedposition',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
