# Generated by Django 3.0.1 on 2019-12-23 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_activities_distinctions', models.BooleanField(default=False)),
                ('get_activities_educations', models.BooleanField(default=False)),
                ('get_activities_employments', models.BooleanField(default=False)),
                ('get_activities_fundings', models.BooleanField(default=False)),
                ('get_activities_invited_positions', models.BooleanField(default=False)),
                ('get_activities_memberships', models.BooleanField(default=False)),
                ('get_activities_peer_reviews', models.BooleanField(default=False)),
                ('get_activities_qualifications', models.BooleanField(default=False)),
                ('get_activities_research_resources', models.BooleanField(default=False)),
                ('get_activities_services', models.BooleanField(default=False)),
                ('get_activities_works', models.BooleanField(default=False)),
                ('get_person_addresses', models.BooleanField(default=False)),
                ('get_person_biography', models.BooleanField(default=False)),
                ('get_person_emails', models.BooleanField(default=False)),
                ('get_person_external_identifiers', models.BooleanField(default=False)),
                ('get_person_keywords', models.BooleanField(default=False)),
                ('get_person_other_names', models.BooleanField(default=False)),
                ('get_person_researcher_urls', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orcid_permission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
