# Generated by Django 3.0.1 on 2020-07-08 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_all_orcid', models.BooleanField(default=False)),
                ('read_all_org1', models.BooleanField(default=False)),
                ('read_all_org2', models.BooleanField(default=False)),
                ('priority_orcid', models.PositiveSmallIntegerField(default=1, null=True)),
                ('priority_org1', models.PositiveSmallIntegerField(default=2, null=True)),
                ('priority_org2', models.PositiveSmallIntegerField(default=3, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orcid_permission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
