# Generated by Django 3.0.1 on 2020-07-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orciddata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='priority_orcid',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='priority_org1',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='priority_org2',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
