<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>CSC.ResearchFi.Mydata.PublicApiContracts</PackageId>
    <Version>0.0.1</Version>
    <Authors>CSC - IT Center for Science</Authors>
    <Description>Request/response contract types for the Research.fi Mydata Public API integration endpoint.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
