# This file is part of the research.fi service
#
# Copyright 2022 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT
apiVersion: v1
kind: Template
metadata:
  labels:
    app: keycloak-qa
    template: keycloak-qa
  name: keycloak-qa
objects:
  # Service (QA)
  - apiVersion: v1
    kind: Service
    metadata:
      name: keycloak-service-qa
      labels:
        app: keycloak-qa
      annotations:
        description: Keycloak service for QA branch
    spec:
      ports:
        - name: keycloak-port-qa
          port: 8080
          targetPort: 8080
      selector:
        depcfg: keycloak-depcfg-qa

  # ImageStream (QA)
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: keycloak-qa
      labels:
        app: keycloak-qa

  # BuildConfig using Docker build strategy
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: keycloak-build-qa
      labels:
        app: keycloak-qa
    spec:
      source:
        git:
          uri: https://github.com/CSCfi/research-fi-mydata.git
          ref: qa
        contextDir: .
      strategy:
        dockerStrategy:
          dockerfilePath: keycloak/openshift/Dockerfile
      output:
        to:
          kind: ImageStreamTag
          name: keycloak-qa:latest
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 2

  # Deployment config (QA)
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: keycloak-deployment-qa
      labels:
        app: keycloak-qa
    spec:
      selector:
        app: keycloak-qa
        depcfg: keycloak-depcfg-qa
      template:
        metadata:
          labels:
            app: keycloak-qa
            depcfg: keycloak-depcfg-qa
        spec:
          containers:
            - name: keycloak-container-qa
              image: researchfi/keycloak-qa
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  protocol: TCP
      replicas: 1
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - keycloak-container-qa
            from:
              kind: ImageStreamTag
              name: keycloak-qa:latest
      strategy:
        type: Recreate