# This file is part of the research.fi service
#
# Copyright 2022 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT
apiVersion: v1
kind: Template
metadata:
  labels:
    app: keycloak-production
    template: keycloak-production
  name: keycloak-production
objects:
  # Service (production)
  - apiVersion: v1
    kind: Service
    metadata:
      name: keycloak-service-production
      labels:
        app: keycloak-production
      annotations:
        description: Keycloak service for production branch (master)
    spec:
      ports:
        - name: keycloak-port-production
          port: 8080
          targetPort: 8080
      selector:
        depcfg: keycloak-depcfg-production

  # ImageStream (production)
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: keycloak-production
      labels:
        app: keycloak-production

  # BuildConfig using Docker build strategy
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: keycloak-build-production
      labels:
        app: keycloak-production
    spec:
      source:
        git:
          uri: https://github.com/CSCfi/research-fi-mydata.git
          ref: master
        contextDir: .
      strategy:
        dockerStrategy:
          dockerfilePath: keycloak/openshift/Dockerfile
      output:
        to:
          kind: ImageStreamTag
          name: keycloak-production:latest
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 2

  # Deployment config (production)
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: keycloak-deployment-production
      labels:
        app: keycloak-production
    spec:
      selector:
        app: keycloak-production
        depcfg: keycloak-depcfg-production
      template:
        metadata:
          labels:
            app: keycloak-production
            depcfg: keycloak-depcfg-production
        spec:
          containers:
            - name: keycloak-container-production
              image: researchfi/keycloak-production
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  protocol: TCP
      replicas: 1
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - keycloak-container-production
            from:
              kind: ImageStreamTag
              name: keycloak-production:latest
      strategy:
        type: Recreate